title: Zijian Niu's Homepage
page-top-title: Zijian Niu
top-section-bg-text: Master's Degree in cross-disciplinary Technologies+
home-subtitle: Zijian Niu&ensp;|&ensp;牛子健
copyright-text: '&copy; Zijian Niu 2024-2025. All Rights Reserved.'
